drop table if exists t_user cascade;
create table if not exists t_user
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
drop table if exists t_user_roles cascade;
create table t_user_roles
(
    user_id  int8 not null,
    roles_id int8 not null,
    primary key (user_id, roles_id)
);